import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 16, paddingTop: 12 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingTop: 52, paddingBottom: 14, borderBottomWidth: 1,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { fontSize: 18, fontWeight: '800', letterSpacing: -0.3 },
  addBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 10, paddingHorizontal: 13, paddingVertical: 8 },
  addBtnTxt: { fontSize: 13, fontWeight: '700' },
  summaryRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  summaryCard: { flex: 1, alignItems: 'center', paddingVertical: 10, paddingHorizontal: 4, borderRadius: 12, borderWidth: 1.5 },
  summaryEmoji: { fontSize: 16, marginBottom: 2 },
  summaryValue: { fontSize: 18, fontWeight: '900', lineHeight: 22 },
  summaryLabel: { fontSize: 9.5, fontWeight: '600', marginTop: 1, textAlign: 'center' },
  searchBar: { flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 10, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 10 },
  searchInput: { flex: 1, fontSize: 14 },
  resultsInfo: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  resultsCount: { fontSize: 12 },
  clearTxt: { fontSize: 12, fontWeight: '700' },
  envCard: { borderRadius: 14, borderWidth: 1.5, borderLeftWidth: 4, overflow: 'hidden', marginBottom: 12 },
  cardTop: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 11 },
  cardIcon: { width: 38, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  cardInfo: { flex: 1 },
  cardName: { fontSize: 15, fontWeight: '700', marginBottom: 3 },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  cardMetaTxt: { fontSize: 11 },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 20, borderWidth: 1, paddingHorizontal: 7, paddingVertical: 3 },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusTxt: { fontSize: 10, fontWeight: '700' },
  metricsRow: { flexDirection: 'row', borderTopWidth: 1 },
  metricCell: { flex: 1, alignItems: 'center', paddingVertical: 10, gap: 2 },
  metricIcon: { fontSize: 14 },
  metricValue: { fontSize: 13, fontWeight: '800', lineHeight: 17 },
  metricLabel: { fontSize: 9.5, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.3 },
  cardActions: { flexDirection: 'row', borderTopWidth: 1 },
  editBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 11, borderRightWidth: 1 },
  editBtnTxt: { fontSize: 13, fontWeight: '600' },
  deleteBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 11 },
  deleteBtnTxt: { fontSize: 13, fontWeight: '600' },
  empty: { alignItems: 'center', paddingTop: 60, gap: 10 },
  emptyIcon: { fontSize: 52 },
  emptyTitle: { fontSize: 17, fontWeight: '800', textAlign: 'center' },
  emptyBtn: { borderRadius: 12, paddingHorizontal: 20, paddingVertical: 11, marginTop: 6 },
  emptyBtnTxt: { fontSize: 14, fontWeight: '700' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  deleteMsg: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
})
