import { createContext, useContext, useEffect, useMemo, useState } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

const LanguageContext = createContext();

const LANGUAGE_NAMES = {
  es: "Espanol",
  en: "English",
};

const STRINGS = {
  es: {
    loading: "Cargando...",
    tabs: {
      home: "Inicio",
      favorites: "Favoritos",
      management: "Gestion",
      alerts: "Alertas",
      environments: "Ambientes",
      profile: "Perfil",
    },
    status: {
      normal: "Normal",
      warning: "Advertencia",
      alert: "Alerta",
    },
    quality: {
      good: "Buena",
      regular: "Regular",
      bad: "Mala",
    },
    common: {
      cancel: "Cancelar",
      save: "Guardar",
      delete: "Eliminar",
      add: "Agregar",
      edit: "Editar",
    },
    dashboard: {
      title: "Ranking de Ambientes",
      subtitle: "Toca un ambiente para ver detalles",
      goodHealth: "Estado general bueno",
      recommendedAttention: "Atencion recomendada",
      interventionNeeded: "Intervencion necesaria",
      monitored: "{{count}} ambientes monitoreados",
      total: "Total",
      all: "Todos",
      noAlerts: "Sin alertas activas - todos los ambientes estan bien",
      activeAlerts: "Alertas activas",
      noise: "Ruido",
      emptyByStatus: "No hay ambientes con este estado",
      searchPlaceholder: "Buscar por nombre...",
      allLocations: "Todos los bloques",
      average: "Promedio",
      best: "Mejor",
      worst: "Peor",
      positions: "Posiciones {{from}} - {{to}}",
      scoreTitle: "Como se calcula el puntaje",
      idealTemp: "Temp ideal: 18-24C",
      idealHumidity: "Humedad ideal: 40-60%",
      idealCo2: "CO2 ideal: < 1000 ppm",
      idealNoise: "Ruido ideal: < 50 dB",
    },
    settings: {
      title: "Configuracion",
      appearance: "Apariencia",
      darkMode: "Modo oscuro",
      accessibleTheme: "Tema accesible",
      accessibilityMenu: "Menu de accesibilidad",
      textSize: "TAMANO DE TEXTO",
      colorMode: "MODO DE COLOR",
      colorVision: "VISION DEL COLOR",
      light: "☀  Claro",
      dark: "☾  Oscuro",
      resetAccessibility: "Restablecer todo",
      languageDates: "Idioma y fechas",
      language: "Idioma",
      dateFormat: "Formato de fecha",
      autoTimezone: "Zona horaria automatica",
      timezone: "Zona horaria:",
      reminders: "Recordatorios",
      criticalAlerts: "Alertas criticas",
      warnings: "Advertencias",
      dailySummary: "Resumen diario",
      sound: "Sonido",
      privacy: "Privacidad",
      publicProfile: "Perfil publico",
      shareData: "Compartir datos",
      changePassword: "Cambiar contrasena",
      deleteAccount: "Eliminar cuenta",
      help: "Ayuda",
      faq: "Preguntas frecuentes",
      contact: "Contacto",
      terms: "Terminos y condiciones",
      privacyPolicy: "Politica de privacidad",
      version: "Version",
      currentPassword: "Contrasena actual",
      newPassword: "Nueva contrasena",
      confirmPassword: "Confirmar contrasena",
      requiredFieldsTitle: "Campos requeridos",
      requiredFieldsMessage: "Completa todos los campos.",
      passwordMismatchTitle: "Error",
      passwordMismatchMessage: "Las contrasenas no coinciden.",
      passwordLengthMessage: "La contrasena debe tener al menos 6 caracteres.",
      passwordSuccessTitle: "Exito",
      passwordSuccessMessage: "Contrasena actualizada correctamente",
      deleteMessage:
        "Estas seguro de eliminar tu cuenta? Esta accion no se puede deshacer.",
      faqAddQuestion: "Como agregar un ambiente?",
      faqAddAnswer: "Ve a Gestion -> Agregar ambiente",
      faqThemeQuestion: "Como cambiar el tema?",
      faqThemeAnswer: "En Configuracion -> Apariencia",
      faqPasswordQuestion: "Olvide mi contrasena?",
      faqPasswordAnswer: 'Usa la opcion "Olvide mi contrasena" en login',
      email: "Correo",
      schedule: "Horario",
      scheduleValue: "L-V 8am-6pm",
      termsText:
        "Al usar EduAirControl, aceptas estas condiciones y el tratamiento de datos informado en ellas.",
      termsUse: "Uso educativo e institucional responsable",
      termsData: "Tratamiento conforme a la Ley 1581 de 2012",
      termsIp: "Respeto por la propiedad intelectual",
      privacyText:
        "Tratamos solo los datos necesarios para prestar y mejorar el servicio.",
      privacyNoShare:
        "Compartimos informacion solo cuando es necesario, autorizado o exigido por ley",
      privacyEncrypted: "Aplicamos medidas razonables de seguridad",
      privacyRights: "Puedes ejercer tus derechos en soporte@eduaircontrol.com",
      versionDate: "Mayo 2026",
      normalTheme: "Normal",
      protanopia: "Protanopia",
      deuteranopia: "Deuteranopia",
      tritanopia: "Tritanopia",
    },
    notifications: {
      title: "Notificaciones",
      activeAlerts: "{{count}} alertas activas",
      all: "Todas",
      alerts: "Alertas",
      warnings: "Advertencias",
      info: "Info",
      emptyTitle: "Sin notificaciones",
      emptyText: "Todos los ambientes estan dentro de los parametros normales",
      highCo2: "CO2 elevado",
      highTemp: "Temperatura alta",
      highNoise: "Ruido elevado",
      humidityOut: "Humedad fuera de rango",
      dailySummary: "Resumen del dia",
      maxRecommended: "max recomendado",
      summaryMessage:
        "{{alerts}} alertas - {{warnings}} advertencias en {{count}} ambientes",
      markAllRead: "Marcar todas como leidas",
    },
    environments: {
      title: "Ambientes",
      subtitle: "Todos los ambientes registrados",
      any: "Cualquiera",
      anyCapacity: "Toda capacidad",
      small: "Hasta 30",
      medium: "31 a 50",
      large: "Mas de 50",
      byName: "Nombre",
      byScore: "Puntaje",
      byCapacity: "Capacidad",
      filters: "Filtros",
      status: "Estado",
      favorite: "Favoritos",
      capacity: "Capacidad",
      sort: "Ordenar",
      clearFilters: "Limpiar filtros",
      seeResults: "Ver {{count}} resultados",
    },
    favorites: {
      title: "Favoritos",
      noneYet: "No tienes ambientes favoritos aun",
      saved: "{{count}} ambiente{{plural}} guardado{{plural}}",
      emptyTitle: "Sin favoritos",
      emptyText:
        "Toca el corazon en cualquier ambiente del dashboard para guardarlo aqui",
      goDashboard: "Ir al Dashboard",
      removeTitle: "Eliminar de favoritos",
      removeQuestion: 'Deseas quitar "{{name}}" de tus favoritos?',
      people: "personas",
      airQuality: "Calidad del aire",
    },
    environmentDetail: {
      title: "Detalle",
      notFound: "Ambiente no encontrado",
      back: "Volver",
      noLocation: "Sin ubicacion",
      people: "Personas",
      airQuality: "Calidad",
      score: "Puntaje",
      attentionNeeded: "Atencion necesaria",
      stable: "Ambiente estable",
      realTimeMetrics: "Metricas en tiempo real",
      dayHistory: "Historial del dia",
      ideal: "Ideal {{range}}",
      recommendationReview: "Revisar {{metrics}}.",
      recommendationOk: "Las condiciones estan dentro del rango recomendado.",
      tempLow: "Temperatura baja: {{value}} C. Ideal {{ideal}}.",
      tempHigh: "Temperatura alta: {{value}} C. Ideal {{ideal}}.",
      humidityLow: "Humedad baja: {{value}}%. Ideal {{ideal}}.",
      humidityHigh: "Humedad alta: {{value}}%. Ideal {{ideal}}.",
      co2High: "CO2 elevado: {{value}} ppm. Ideal {{ideal}}.",
      noiseHigh: "Ruido elevado: {{value}} dB. Ideal {{ideal}}.",
      outOfRange: "{{metric}} fuera del rango recomendado.",
      temperature: "Temperatura",
      humidity: "Humedad",
      noise: "Ruido",
      perceivedComfort: "Confort percibido",
      ratingQuestion:
        "Califica como se siente este ambiente para estudiar o trabajar.",
      submitRating: "Enviar calificacion",
      ratingSubmitted: "Calificacion enviada. Gracias por tu opinion.",
    },
    profile: {
      title: "Mi Perfil",
      personalInfo: "Informacion personal",
      fullName: "Nombre completo",
      email: "Correo electronico",
      role: "Cargo / Rol",
      phone: "Telefono",
      location: "Ubicacion",
      logout: "Cerrar sesion",
      logoutQuestion: "Estas seguro de que quieres salir?",
      exit: "Salir",
      edit: "Editar {{label}}",
      placeholder: "Ingresa {{label}}",
    },
    management: {
      title: "Gestion de Ambientes",
      add: "Agregar",
      warning: "Advertencia",
      searchPlaceholder: "Buscar por nombre o ubicacion...",
      showing: "Mostrando {{shown}} de {{total}} ambientes",
      clear: "Limpiar",
      noResults: "Sin resultados",
      noEnvironments: "Sin ambientes",
      tryAnother: "Intenta con otro termino o cambia los filtros",
      startMonitoring: 'Toca "Agregar" para comenzar a monitorear',
      clearSearch: "Limpiar busqueda",
      capacityLabel: "Capacidad:",
      min: "Min",
      max: "Max",
      sort: "Ordenar",
      sortName: "Nombre",
      sortCapacity: "Capacidad",
      sortStatus: "Estado",
      addEnvironment: "Agregar ambiente",
      newEnvironment: "Nuevo ambiente",
      editEnvironment: "Editar ambiente",
      name: "Nombre *",
      capacity: "Capacidad",
      location: "Ubicacion",
      requiredTitle: "Campo requerido",
      requiredName: "El nombre del ambiente es obligatorio.",
      noLocation: "Sin ubicacion",
      deleteTitle: "Eliminar ambiente",
      deleteQuestion: 'Eliminar "{{name}}"? Esta accion no se puede deshacer.',
    },
    landing: {
      healthyAir: "AIRE MAS SALUDABLE",
      heroTitle: "El aire tambien",
      heroAccent: "educa.",
      heroDescription:
        "EduAirControl transforma la calidad del aire en informacion accionable para crear espacios mas sanos y productivos.",
      createAccount: "Crear cuenta",
      explore: "Explorar",
      monitoring: "monitoreo",
      traceability: "trazabilidad",
      centralView: "vista central",
      environmentalSummary: "Resumen ambiental",
      live: "EN VIVO",
      airQuality: "Calidad del aire · ultimas 24 h",
      iaq: "IAQ",
      co2: "CO2 ppm",
      humidity: "Humedad",
      whyEyebrow: "Por que elegirnos",
      whyTitle: "Bienestar que se",
      whyAccent: "puede medir",
      whyDescription:
        "Una plataforma diseñada para que cada lectura se convierta en una mejora concreta.",
      designedEyebrow: "Pensado para",
      designedTitle: "Espacios que",
      designedAccent: "cuidan",
      designedDescription:
        "EduAirControl acompaña a quienes hacen que cada ambiente funcione mejor.",
      ctaTitle: "Empieza a cuidar tu aire.",
      ctaDescription:
        "Convierte tus espacios en ambientes mas saludables desde hoy.",
      startNow: "Comenzar ahora",
      footerDescription: "Tecnologia para ambientes que inspiran.",
      navigation: "Navegacion",
      home: "Inicio",
      signIn: "Ingresar",
      accessibility: "Accesibilidad",
      openNavigation: "Abrir menu de navegacion",
      closeNavigation: "Cerrar menu de navegacion",
      previous: "Anterior",
      next: "Siguiente",
      benefit: "Ver beneficio",
      audience: "Ver publico",
      features: {
        feature1Title: "Monitoreo inteligente",
        feature1Text:
          "Sensores conectados que convierten el aire de tus espacios en decisiones claras.",
        feature2Title: "Alertas en tiempo real",
        feature2Text:
          "Recibe avisos oportunos antes de que una condicion afecte a tu comunidad.",
        feature3Title: "Datos que explican",
        feature3Text:
          "Visualiza tendencias, compara ambientes y encuentra oportunidades de mejora.",
        feature4Title: "Gestion confiable",
        feature4Text:
          "Una plataforma pensada para cuidar personas, espacios y operaciones.",
      },
      audiences: {
        audience1Title: "Instituciones educativas",
        audience1Text: "Ambientes preparados para aprender.",
        audience2Title: "Administradores",
        audience2Text: "Una vista para decidir mejor.",
        audience3Title: "Comunidades",
        audience3Text: "Bienestar medible para todos.",
      },
    },
    auth: {
      loginTitle: "Iniciar sesion",
      signupTitle: "Registrarse",
      emailLabel: "Correo electronico",
      emailPlaceholder: "correo@ejemplo.com",
      passwordLabel: "Contrasena",
      confirmPasswordLabel: "Confirmar contrasena",
      passwordPlaceholder: "********",
      nameLabel: "Nombre",
      namePlaceholder: "Tu nombre",
      rememberMe: "Recordarme",
      forgotPassword: "Olvide mi contrasena?",
      loginBtn: "Iniciar sesion",
      registerBtn: "Registrarse",
      orContinueWith: "o continua con",
      noAccount: "No tienes cuenta? ",
      hasAccount: "Ya tienes cuenta? ",
      signupLink: "Registrate",
      loginLink: "Iniciar sesion",
      forgotTitle: "Recuperar contrasena",
      forgotDescription:
        "Ingresa tu correo y te enviaremos un enlace para restablecer tu contrasena.",
      submitLink: "Enviar enlace",
      backToLogin: "Volver al inicio de sesion",
      successMessage: "Consulta tu correo. Hemos enviado las instrucciones.",
      verifyTitle: "Verificar codigo",
      verifyDescription:
        "Ingresa el codigo de 6 digitos que enviamos a tu correo.",
      codeLabel: "Codigo de verificacion",
      codePlaceholder: "000000",
      verifyBtn: "Verificar",
      termsTitle: "Terminos y Condiciones",
      termsSection1: "1. Uso de la aplicacion",
      termsText1:
        "EduAirControl es una herramienta educativa para monitorear la calidad del aire en ambientes academicos. Su uso esta destinado exclusivamente a fines educativos e institucionales.",
      termsSection2: "2. Privacidad de datos",
      termsText2:
        "Los datos recopilados se utilizan unicamente para mejorar la experiencia del usuario y el monitoreo ambiental. No se comparten con terceros sin consentimiento explicito.",
      termsSection3: "3. Responsabilidades",
      termsText3:
        "El usuario es responsable del uso adecuado de la aplicacion y de mantener sus credenciales seguras.",
      termsSection4: "4. Tratamiento de datos personales",
      termsText4:
        "EduAirControl tratara los datos necesarios para crear y administrar la cuenta, prestar el servicio, atender solicitudes y generar informacion sobre los ambientes monitoreados. El tratamiento se realizara conforme a la Ley 1581 de 2012, el Decreto 1074 de 2015 y las demas normas colombianas aplicables.",
      termsSection5: "5. Derechos del titular",
      termsText5:
        "Puedes conocer, actualizar, rectificar o solicitar la supresion de tus datos, y revocar la autorizacion cuando proceda. Para ejercer tus derechos o presentar consultas y reclamos, escribe a soporte@eduaircontrol.com. La solicitud se gestionara dentro de los plazos legales aplicables.",
      termsSection6: "6. Seguridad y terceros",
      termsText6:
        "Aplicaremos medidas razonables de seguridad y solo compartiremos informacion cuando sea necesario para prestar el servicio, exista autorizacion, una obligacion legal o una orden de autoridad competente. No solicitamos datos sensibles para usar las funciones basicas de la aplicacion.",
      termsSection7: "7. Alcance de las mediciones",
      termsText7:
        "Las lecturas ambientales son orientativas y dependen de los sensores, su instalacion y conectividad. No sustituyen una evaluacion sanitaria, tecnica o de seguridad profesional. El usuario debe tomar las decisiones operativas que correspondan frente a riesgos identificados.",
      termsSection8: "8. Contacto y cambios",
      termsText8:
        "Para soporte, privacidad o solicitudes relacionadas con estos terminos, contacta a soporte@eduaircontrol.com. Podremos actualizar estas condiciones para reflejar cambios legales o funcionales y publicaremos la version vigente en la aplicacion.",
      termsUpdated: "Ultima actualizacion: agosto de 2026",
      acceptBtn: "Aceptar y continuar",
      changePasswordTitle: "Cambiar contrasena",
      currentPasswordLabel: "Contrasena actual",
      newPasswordLabel: "Nueva contrasena",
      confirmNewPasswordLabel: "Confirmar nueva contrasena",
      required: "Requerido",
      noMatch: "No coincide",
      validationTitle: "Revisa los datos",
      requiredLogin: "Completa el correo y la contrasena.",
      requiredRegister: "Completa todos los campos del registro.",
      invalidEmail: "Ingresa un correo electronico valido.",
      passwordLength: "La contrasena debe tener al menos 6 caracteres.",
      acceptTermsRequired: "Debes aceptar los terminos y condiciones.",
      invalidCode: "Ingresa un codigo numerico de 6 digitos.",
      passwordSuccess: "Contrasena actualizada correctamente",
      saveChangesBtn: "Guardar cambios",
      acceptTerms: "Acepto los",
      termsAndPrivacy: "Terminos de uso y Politica de privacidad",
      googleChooseAccount: "Elige una cuenta",
      googleCompanyCode: "Codigo de empresa",
      googleSelectAccount:
        "Selecciona la cuenta de Google con la que quieres registrarte en EduAirControl",
      googleCodeLabel: "Codigo de empresa",
      googlePlaceholder: "Ej: EDU-2024",
      googleConfirmBtn: "Completar registro",
      facebookTitle: "Registro con Facebook",
      facebookConnected: "Cuenta conectada",
      facebookDescription:
        "Tu cuenta de Facebook ha sido verificada. Ingresa el codigo de tu institucion para continuar.",
      facebookCodeLabel: "Codigo de empresa *",
      facebookTerms: "Acepto los terminos y condiciones",
      facebookConfirmBtn: "Completar registro",
    },
  },
  en: {
    loading: "Loading...",
    tabs: {
      home: "Home",
      favorites: "Favorites",
      management: "Manage",
      alerts: "Alerts",
      environments: "Environments",
      profile: "Profile",
    },
    status: {
      normal: "Normal",
      warning: "Warning",
      alert: "Alert",
    },
    quality: {
      good: "Good",
      regular: "Fair",
      bad: "Poor",
    },
    common: {
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      add: "Add",
      edit: "Edit",
    },
    dashboard: {
      title: "Environment Ranking",
      subtitle: "Tap an environment to view details",
      goodHealth: "Overall status is good",
      recommendedAttention: "Attention recommended",
      interventionNeeded: "Intervention needed",
      monitored: "{{count}} environments monitored",
      total: "Total",
      all: "All",
      noAlerts: "No active alerts - all environments are OK",
      activeAlerts: "Active alerts",
      noise: "Noise",
      emptyByStatus: "No environments with this status",
      searchPlaceholder: "Search by name...",
      allLocations: "All buildings",
      average: "Average",
      best: "Best",
      worst: "Worst",
      positions: "Positions {{from}} - {{to}}",
      scoreTitle: "How the score is calculated",
      idealTemp: "Ideal temp: 18-24C",
      idealHumidity: "Ideal humidity: 40-60%",
      idealCo2: "Ideal CO2: < 1000 ppm",
      idealNoise: "Ideal noise: < 50 dB",
    },
    settings: {
      title: "Settings",
      appearance: "Appearance",
      darkMode: "Dark mode",
      accessibleTheme: "Accessible theme",
      accessibilityMenu: "Accessibility menu",
      textSize: "TEXT SIZE",
      colorMode: "COLOR MODE",
      colorVision: "COLOR VISION",
      light: "☀  Light",
      dark: "☾  Dark",
      resetAccessibility: "Reset all",
      languageDates: "Language and dates",
      language: "Language",
      dateFormat: "Date format",
      autoTimezone: "Automatic time zone",
      timezone: "Time zone:",
      reminders: "Reminders",
      criticalAlerts: "Critical alerts",
      warnings: "Warnings",
      dailySummary: "Daily summary",
      sound: "Sound",
      privacy: "Privacy",
      publicProfile: "Public profile",
      shareData: "Share data",
      changePassword: "Change password",
      deleteAccount: "Delete account",
      help: "Help",
      faq: "FAQ",
      contact: "Contact",
      terms: "Terms and conditions",
      privacyPolicy: "Privacy policy",
      version: "Version",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      requiredFieldsTitle: "Required fields",
      requiredFieldsMessage: "Complete all fields.",
      passwordMismatchTitle: "Error",
      passwordMismatchMessage: "Passwords do not match.",
      passwordLengthMessage: "Password must be at least 6 characters.",
      passwordSuccessTitle: "Success",
      passwordSuccessMessage: "Password updated successfully",
      deleteMessage:
        "Are you sure you want to delete your account? This action cannot be undone.",
      faqAddQuestion: "How do I add an environment?",
      faqAddAnswer: "Go to Manage -> Add environment",
      faqThemeQuestion: "How do I change the theme?",
      faqThemeAnswer: "Go to Settings -> Appearance",
      faqPasswordQuestion: "Forgot your password?",
      faqPasswordAnswer: 'Use the "Forgot password" option on login',
      email: "Email",
      schedule: "Hours",
      scheduleValue: "Mon-Fri 8am-6pm",
      termsText:
        "By using EduAirControl, you accept these conditions and the data processing described in them.",
      termsUse: "Responsible educational and institutional use",
      termsData: "Processing under Colombian Law 1581 of 2012",
      termsIp: "Respect for intellectual property",
      privacyText:
        "We process only the data needed to provide and improve the service.",
      privacyNoShare:
        "Information is shared only when necessary, authorized or required by law",
      privacyEncrypted: "We apply reasonable security measures",
      privacyRights:
        "You can exercise your rights at soporte@eduaircontrol.com",
      versionDate: "May 2026",
      normalTheme: "Normal",
      protanopia: "Protanopia",
      deuteranopia: "Deuteranopia",
      tritanopia: "Tritanopia",
    },
    notifications: {
      title: "Notifications",
      activeAlerts: "{{count}} active alerts",
      all: "All",
      alerts: "Alerts",
      warnings: "Warnings",
      info: "Info",
      emptyTitle: "No notifications",
      emptyText: "All environments are within normal parameters",
      highCo2: "High CO2",
      highTemp: "High temperature",
      highNoise: "High noise",
      humidityOut: "Humidity out of range",
      dailySummary: "Daily summary",
      maxRecommended: "recommended max",
      summaryMessage:
        "{{alerts}} alerts - {{warnings}} warnings across {{count}} environments",
      markAllRead: "Mark all as read",
    },
    environments: {
      title: "Environments",
      subtitle: "All registered environments",
      any: "Any",
      anyCapacity: "Any capacity",
      small: "Up to 30",
      medium: "31 to 50",
      large: "Over 50",
      byName: "Name",
      byScore: "Score",
      byCapacity: "Capacity",
      filters: "Filters",
      status: "Status",
      favorite: "Favorites",
      capacity: "Capacity",
      sort: "Sort",
      clearFilters: "Clear filters",
      seeResults: "See {{count}} results",
    },
    favorites: {
      title: "Favorites",
      noneYet: "You do not have favorite environments yet",
      saved: "{{count}} saved environment{{plural}}",
      emptyTitle: "No favorites",
      emptyText: "Tap the heart on any dashboard environment to save it here",
      goDashboard: "Go to Dashboard",
      removeTitle: "Remove from favorites",
      removeQuestion: 'Remove "{{name}}" from your favorites?',
      people: "people",
      airQuality: "Air quality",
    },
    environmentDetail: {
      title: "Detail",
      notFound: "Environment not found",
      back: "Back",
      noLocation: "No location",
      people: "People",
      airQuality: "Quality",
      score: "Score",
      attentionNeeded: "Attention needed",
      stable: "Stable environment",
      realTimeMetrics: "Real-time metrics",
      dayHistory: "Today history",
      ideal: "Ideal {{range}}",
      recommendationReview: "Review {{metrics}}.",
      recommendationOk: "Conditions are within the recommended range.",
      tempLow: "Low temperature: {{value}} C. Ideal {{ideal}}.",
      tempHigh: "High temperature: {{value}} C. Ideal {{ideal}}.",
      humidityLow: "Low humidity: {{value}}%. Ideal {{ideal}}.",
      humidityHigh: "High humidity: {{value}}%. Ideal {{ideal}}.",
      co2High: "High CO2: {{value}} ppm. Ideal {{ideal}}.",
      noiseHigh: "High noise: {{value}} dB. Ideal {{ideal}}.",
      outOfRange: "{{metric}} is outside the recommended range.",
      temperature: "Temperature",
      humidity: "Humidity",
      noise: "Noise",
      perceivedComfort: "Perceived comfort",
      ratingQuestion:
        "Rate how this environment feels for studying or working.",
      submitRating: "Submit rating",
      ratingSubmitted: "Rating submitted. Thanks for your feedback.",
    },
    profile: {
      title: "My Profile",
      personalInfo: "Personal information",
      fullName: "Full name",
      email: "Email",
      role: "Job / Role",
      phone: "Phone",
      location: "Location",
      logout: "Log out",
      logoutQuestion: "Are you sure you want to leave?",
      exit: "Exit",
      edit: "Edit {{label}}",
      placeholder: "Enter {{label}}",
    },
    management: {
      title: "Environment Management",
      add: "Add",
      warning: "Warning",
      searchPlaceholder: "Search by name or location...",
      showing: "Showing {{shown}} of {{total}} environments",
      clear: "Clear",
      noResults: "No results",
      noEnvironments: "No environments",
      tryAnother: "Try another term or change the filters",
      startMonitoring: 'Tap "Add" to start monitoring',
      clearSearch: "Clear search",
      capacityLabel: "Capacity:",
      min: "Min",
      max: "Max",
      sort: "Sort",
      sortName: "Name",
      sortCapacity: "Capacity",
      sortStatus: "Status",
      addEnvironment: "Add environment",
      newEnvironment: "New environment",
      editEnvironment: "Edit environment",
      name: "Name *",
      capacity: "Capacity",
      location: "Location",
      requiredTitle: "Required field",
      requiredName: "Environment name is required.",
      noLocation: "No location",
      deleteTitle: "Delete environment",
      deleteQuestion: 'Delete "{{name}}"? This action cannot be undone.',
    },
    landing: {
      healthyAir: "HEALTHIER AIR",
      heroTitle: "Air also",
      heroAccent: "educates.",
      heroDescription:
        "EduAirControl turns air quality into actionable information to create healthier and more productive spaces.",
      createAccount: "Create account",
      explore: "Explore",
      monitoring: "monitoring",
      traceability: "traceability",
      centralView: "central view",
      environmentalSummary: "Environmental summary",
      live: "LIVE",
      airQuality: "Air quality · last 24 hours",
      iaq: "IAQ",
      co2: "CO2 ppm",
      humidity: "Humidity",
      whyEyebrow: "Why choose us",
      whyTitle: "Wellbeing you can",
      whyAccent: "measure",
      whyDescription:
        "A platform designed to turn every reading into a concrete improvement.",
      designedEyebrow: "Designed for",
      designedTitle: "Spaces that",
      designedAccent: "care",
      designedDescription:
        "EduAirControl supports those who make every environment work better.",
      ctaTitle: "Start caring for your air.",
      ctaDescription: "Turn your spaces into healthier environments today.",
      startNow: "Get started",
      footerDescription: "Technology for inspiring environments.",
      navigation: "Navigation",
      home: "Home",
      signIn: "Log in",
      accessibility: "Accessibility",
      openNavigation: "Open navigation menu",
      closeNavigation: "Close navigation menu",
      previous: "Previous",
      next: "Next",
      benefit: "View benefit",
      audience: "View audience",
      features: {
        feature1Title: "Smart monitoring",
        feature1Text:
          "Connected sensors turn the air in your spaces into clear decisions.",
        feature2Title: "Real-time alerts",
        feature2Text:
          "Get timely warnings before a condition affects your community.",
        feature3Title: "Data that explains",
        feature3Text:
          "See trends, compare environments and find opportunities to improve.",
        feature4Title: "Reliable management",
        feature4Text:
          "A platform designed to care for people, spaces and operations.",
      },
      audiences: {
        audience1Title: "Educational institutions",
        audience1Text: "Environments ready for learning.",
        audience2Title: "Administrators",
        audience2Text: "One view for better decisions.",
        audience3Title: "Communities",
        audience3Text: "Measurable wellbeing for everyone.",
      },
    },
    auth: {
      loginTitle: "Log in",
      signupTitle: "Sign up",
      emailLabel: "Email",
      emailPlaceholder: "email@example.com",
      passwordLabel: "Password",
      confirmPasswordLabel: "Confirm password",
      passwordPlaceholder: "********",
      nameLabel: "Name",
      namePlaceholder: "Your name",
      rememberMe: "Remember me",
      forgotPassword: "Forgot your password?",
      loginBtn: "Log in",
      registerBtn: "Sign up",
      orContinueWith: "or continue with",
      noAccount: "Don't have an account? ",
      hasAccount: "Already have an account? ",
      signupLink: "Sign up",
      loginLink: "Log in",
      forgotTitle: "Forgot password",
      forgotDescription:
        "Enter your email and we will send you a link to reset your password.",
      submitLink: "Send link",
      backToLogin: "Back to login",
      successMessage: "Check your email. We have sent the instructions.",
      verifyTitle: "Verify code",
      verifyDescription: "Enter the 6-digit code we sent to your email.",
      codeLabel: "Verification code",
      codePlaceholder: "000000",
      verifyBtn: "Verify",
      termsTitle: "Terms and Conditions",
      termsSection1: "1. Use of the application",
      termsText1:
        "EduAirControl is an educational tool for monitoring air quality in academic environments. Its use is exclusively for educational and institutional purposes.",
      termsSection2: "2. Data privacy",
      termsText2:
        "Collected data is used solely to improve user experience and environmental monitoring. It is not shared with third parties without explicit consent.",
      termsSection3: "3. Responsibilities",
      termsText3:
        "The user is responsible for the proper use of the application and for keeping their credentials secure.",
      termsSection4: "4. Personal data processing",
      termsText4:
        "EduAirControl will process the data needed to create and manage your account, provide the service, handle requests and generate information about monitored environments. Processing will comply with Colombian Law 1581 of 2012, Decree 1074 of 2015 and other applicable regulations.",
      termsSection5: "5. Data subject rights",
      termsText5:
        "You may access, update, correct or request deletion of your data, and withdraw consent where applicable. To exercise your rights or submit questions and complaints, email soporte@eduaircontrol.com. Requests will be handled within applicable legal deadlines.",
      termsSection6: "6. Security and third parties",
      termsText6:
        "We will apply reasonable security measures and only share information when needed to provide the service, when authorized, required by law or ordered by a competent authority. We do not require sensitive data for the application's basic features.",
      termsSection7: "7. Measurement scope",
      termsText7:
        "Environmental readings are informational and depend on sensors, installation and connectivity. They do not replace a professional health, technical or safety assessment. Users must take the operational decisions required when risks are identified.",
      termsSection8: "8. Contact and changes",
      termsText8:
        "For support, privacy or requests related to these terms, contact soporte@eduaircontrol.com. We may update these conditions to reflect legal or functional changes and will publish the current version in the application.",
      termsUpdated: "Last updated: August 2026",
      acceptBtn: "Accept and continue",
      changePasswordTitle: "Change password",
      currentPasswordLabel: "Current password",
      newPasswordLabel: "New password",
      confirmNewPasswordLabel: "Confirm new password",
      required: "Required",
      noMatch: "Does not match",
      validationTitle: "Check your details",
      requiredLogin: "Enter your email and password.",
      requiredRegister: "Complete all registration fields.",
      invalidEmail: "Enter a valid email address.",
      passwordLength: "Password must be at least 6 characters.",
      acceptTermsRequired: "You must accept the terms and conditions.",
      invalidCode: "Enter a 6-digit numeric code.",
      passwordSuccess: "Password updated successfully",
      saveChangesBtn: "Save changes",
      acceptTerms: "I accept the",
      termsAndPrivacy: "Terms of use and Privacy policy",
      googleChooseAccount: "Choose an account",
      googleCompanyCode: "Company code",
      googleSelectAccount:
        "Select the Google account you want to register with on EduAirControl",
      googleCodeLabel: "Company code",
      googlePlaceholder: "Ex: EDU-2024",
      googleConfirmBtn: "Complete registration",
      facebookTitle: "Sign up with Facebook",
      facebookConnected: "Account connected",
      facebookDescription:
        "Your Facebook account has been verified. Enter your institution code to continue.",
      facebookCodeLabel: "Company code *",
      facebookTerms: "I accept the terms and conditions",
      facebookConfirmBtn: "Complete registration",
    },
  },
};

function normalizeLanguage(value) {
  if (!value) return "es";
  const clean = String(value).toLowerCase();
  if (clean.startsWith("en") || clean.includes("english")) return "en";
  return "es";
}

function getValue(path, language) {
  return path
    .split(".")
    .reduce((current, part) => current?.[part], STRINGS[language]);
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("es");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const saved = await AsyncStorage.getItem("settings");
        if (saved) {
          const parsed = JSON.parse(saved);
          setLanguageState(normalizeLanguage(parsed.language));
        }
      } catch (e) {
        console.warn("Error loading language:", e);
      } finally {
        setLoaded(true);
      }
    };
    load();
  }, []);

  const setLanguage = async (nextLanguage) => {
    const normalized = normalizeLanguage(nextLanguage);
    setLanguageState(normalized);
    try {
      const saved = await AsyncStorage.getItem("settings");
      const parsed = saved ? JSON.parse(saved) : {};
      await AsyncStorage.setItem(
        "settings",
        JSON.stringify({ ...parsed, language: normalized }),
      );
    } catch (e) {
      console.warn("Error saving language:", e);
    }
  };

  const value = useMemo(() => {
    const t = (key, params = {}) => {
      const template = getValue(key, language) ?? getValue(key, "es") ?? key;
      if (typeof template !== "string") return key;
      return Object.entries(params).reduce(
        (text, [param, val]) => text.split(`{{${param}}}`).join(String(val)),
        template,
      );
    };

    return {
      language,
      languageName: LANGUAGE_NAMES[language],
      languageOptions: LANGUAGE_NAMES,
      loaded,
      setLanguage,
      t,
    };
  }, [language, loaded]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
