import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingTop: 52, paddingBottom: 12,
  },
  headerTitle: { fontSize: 17, fontWeight: '800' },
  iconButton: { width: 40, height: 40, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1 },
  scrollContent: { padding: 18, paddingTop: 8 },
  heroCard: { borderRadius: 18, borderWidth: 1, padding: 16, marginBottom: 12 },
  heroTop: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  roomIcon: { width: 58, height: 58, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  heroTitleBlock: { flex: 1 },
  roomName: { fontSize: 23, fontWeight: '900', lineHeight: 29 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 5 },
  metaText: { fontSize: 13, fontWeight: '600', flex: 1 },
  badgeRow: { flexDirection: 'row', gap: 8, marginTop: 14, flexWrap: 'wrap' },
  statusBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6,
  },
  statusBadgeText: { fontSize: 12, fontWeight: '800' },
  heroStats: { flexDirection: 'row', alignItems: 'center', marginTop: 16, paddingTop: 14, borderTopWidth: 1 },
  heroStat: { flex: 1, alignItems: 'center' },
  heroStatValue: { fontSize: 18, fontWeight: '900' },
  heroStatLabel: { fontSize: 11, fontWeight: '700', marginTop: 2 },
  heroDivider: { width: 1, height: 34 },
  insightCard: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 10,
    borderRadius: 14, borderWidth: 1, padding: 14, marginBottom: 16,
  },
  insightTitle: { fontSize: 14, fontWeight: '900', marginBottom: 2 },
  insightText: { fontSize: 13, lineHeight: 18 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 10 },
  sectionTitle: { fontSize: 16, fontWeight: '900' },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  metricTile: {
    width: '48.5%', minHeight: 146, borderRadius: 15, borderWidth: 1, padding: 12,
  },
  metricTileTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  metricIconBox: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  metricLabel: { fontSize: 12, fontWeight: '800', flex: 1 },
  metricValue: { fontSize: 20, fontWeight: '900', marginBottom: 10 },
  progressTrack: { height: 7, borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
  progressFill: { height: '100%', borderRadius: 4 },
  metricFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  idealText: { fontSize: 10.5, fontWeight: '700', flex: 1 },
  infoCard: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderRadius: 14, borderWidth: 1, padding: 14, marginBottom: 16,
  },
  infoText: { flex: 1, fontSize: 14, fontWeight: '600' },
})
