import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  flex: { flex: 1 },
  container: { flexGrow: 1, padding: 24, paddingBottom: 48 },
  back: { position: 'absolute', top: 64, left: 20, zIndex: 2 },
  langRow: { position: 'absolute', top: 64, right: 20, zIndex: 2 },
  title: { fontSize: 26, fontWeight: '800', marginTop: 108, marginBottom: 6, textAlign: 'center' },
  subtitle: { fontSize: 14, marginBottom: 28, textAlign: 'center' },
  form: { gap: 14, marginTop: 4 },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  fieldIcon: { marginRight: 10 },
  fieldInput: { flex: 1, fontSize: 15, padding: 0 },
  errorText: { fontSize: 12, marginTop: 4, marginLeft: 4 },
  errorBanner: { fontSize: 13, marginTop: 16, textAlign: 'center' },
  strengthRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  strengthBar: { flex: 1, height: 4, borderRadius: 2, overflow: 'hidden' },
  strengthFill: { height: 4 },
  strengthLabel: { fontSize: 12 },
termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: 10,
    marginTop: 18,
    paddingRight: 4,
  },
  termsCheck: { marginTop: 2 },
  termsAccept: { fontSize: 14, flex: 1 },
  link: { fontSize: 14, fontWeight: '600' },
  submit: { marginTop: 26 },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 14 },
  switchText: { fontSize: 14 },
  termsIntro: { fontSize: 13, marginBottom: 10 },
  termsSubtitle: { fontSize: 12, fontWeight: '600', marginBottom: 8, textAlign: 'center' },
  termsScroll: { flexShrink: 1, maxHeight: 360 },
  termListItem: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  termParagraph: { fontSize: 13, lineHeight: 19, flex: 1 },
  termNote: { fontSize: 12, fontStyle: 'italic', marginTop: 4 },
  termsBtn: { marginTop: 12 },
})
