import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingHorizontal: 20, paddingTop: 55, paddingBottom: 16,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 18, fontWeight: '800' },
  headerSub: { fontSize: 12, marginTop: 1 },
  iconBtn: {
    width: 40, height: 40, borderRadius: 12, borderWidth: 1,
    alignItems: 'center', justifyContent: 'center',
  },
  scroll: { flex: 1 },
  content: { padding: 16 },
  searchBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderWidth: 1, borderRadius: 12,
    paddingHorizontal: 13, paddingVertical: 11,
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 14 },
  controlsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  filterButton: {
    flex: 1.2, minHeight: 48, borderWidth: 1, borderRadius: 13,
    paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
  },
  filterButtonText: { fontSize: 14, fontWeight: '900' },
  filterBadge: {
    minWidth: 22, height: 22, borderRadius: 11,
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6,
  },
  filterBadgeText: { fontSize: 11, fontWeight: '900' },
  quickSortButton: {
    flex: 1, minHeight: 48, borderWidth: 1, borderRadius: 13,
    paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6,
  },
  quickSortText: { fontSize: 13, fontWeight: '800' },
  resultCount: { fontSize: 12, fontWeight: '700', marginBottom: 10, marginTop: 2 },
  card: {
    flexDirection: 'row', alignItems: 'center', gap: 11,
    borderRadius: 14, borderWidth: 1.5, borderLeftWidth: 4,
    padding: 13, marginBottom: 10,
  },
  iconBox: { width: 40, height: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  cardInfo: { flex: 1 },
  cardName: { fontSize: 15, fontWeight: '800', marginBottom: 5 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { fontSize: 11, maxWidth: 130 },
  rightSide: { alignItems: 'center', gap: 3 },
  scorePill: { width: 42, height: 42, borderRadius: 21, borderWidth: 3, alignItems: 'center', justifyContent: 'center' },
  scoreText: { fontSize: 12, fontWeight: '900' },
  statusText: { fontSize: 10, fontWeight: '800' },
  empty: { alignItems: 'center', paddingTop: 52, gap: 12 },
  emptyTitle: { fontSize: 17, fontWeight: '800', textAlign: 'center' },
  emptyBtn: { borderRadius: 12, paddingHorizontal: 20, paddingVertical: 11 },
  emptyBtnTxt: { fontSize: 14, fontWeight: '700' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.55)' },
  filterSheet: { minHeight: '62%', maxHeight: '78%', borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: 'hidden' },
  sheetBody: { flex: 1, flexDirection: 'row' },
  sectionMenu: { width: 135, borderRightWidth: 1 },
  sectionItem: { minHeight: 74, borderBottomWidth: 1, justifyContent: 'center', paddingHorizontal: 16 },
  sectionIndicator: {
    position: 'absolute', left: 0, top: 14, bottom: 14, width: 3,
    borderTopRightRadius: 3, borderBottomRightRadius: 3,
  },
  sectionText: { fontSize: 14, fontWeight: '800', lineHeight: 18 },
  optionsPane: { flex: 1, paddingHorizontal: 22, paddingTop: 26 },
  optionsTitle: { fontSize: 22, fontWeight: '900', marginBottom: 14 },
  optionRow: { minHeight: 62, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  radioDot: { width: 10, height: 10, borderRadius: 5 },
  optionText: { flex: 1, fontSize: 17, fontWeight: '700' },
  sheetFooter: {
    borderTopWidth: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 18,
    flexDirection: 'row', gap: 12,
  },
  clearButton: { flex: 1, minHeight: 50, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  clearButtonText: { fontSize: 15, fontWeight: '900' },
  resultsButton: { flex: 1.5, minHeight: 50, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  resultsButtonText: { fontSize: 15, fontWeight: '900' },
})
